name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, feature/* ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: xcodebuild test -project HackerNewsApp2023.xcodeproj/ -scheme HackerNewsApp2023 -resultBundlePath TestResults -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 15"
        
      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: TestResults.xcresult
        if: success() || failure()
